version: "2.18.1"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    command:
      - "python"
      - "task_1.py"
#  sentry:
#    image: sentry:latest
#    ports:
#      - "9000:9000"

